### ISSUE TITLE
Pypi version up-to-date?

### ISSUE THREAD

**Issue by nickoala** [MartijnBraam/gpsd-py3#11]
Thanks for accepting my PR #10 

As far as I can see, the current github version of `gpsd-py3` has at least two improvements over the version on pypi (uploaded on 2016-08-05):

- method `get_time()` instead of `time()`
- handling of no `satellites` field (the PR recently accepted)

**Any chance we can get the new and improved `gpsd-py3` on pypi?** I think it's worthwhile to make the improvements more conveniently available to users.

Personally, I am teaching a Raspberry Pi course in which students have to interface a Pi with a GPS sensor. The course is based on Python 3. After surveying Github for gps libraries that works on Python 3, I realize there is not many choices. I settled on `gpsd-py3` because of its simplicity and easy-to-understand API. I think it is a good educational resource.

So, it would be great if the pypi version can be made up-to-date, if that's not too much trouble. Thank you :blush:

**Comment by MartijnBraam** [comment]
I've pushed version 0.3.0 to pypi now, had to figure out how that worked again first. 

Thanks for using my library for educational stuff! I've created it because I wasn't happy at all with the API of the current python modules.
